# Generated by Django 3.2.6 on 2021-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'created'), ('D', 'delivering'), ('A', 'arrived'), ('H', 'handed')], default=('P', 'pending'), max_length=1),
        ),
    ]
