# Generated by Django 3.2.6 on 2021-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210925_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='static/category_icons', verbose_name='Иконка категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.FileField(blank=True, null=True, upload_to='static/photos', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='static/models', verbose_name='3D модель'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='static/shop_covers', verbose_name='Обложка магазина'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/avatars', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/avatars', verbose_name='Изображение профиля'),
        ),
    ]
