# Generated by Django 3.2.6 on 2021-11-03 10:07

from django.db import migrations, models
import django.db.models.deletion
import shop.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210928_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parental_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cart',
            field=models.OneToOneField(auto_created=True, default=shop.models.order.create_cart, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shop.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sellerprofile', verbose_name='Продавец'),
        ),
    ]
