# Generated by Django 3.2.6 on 2021-11-03 10:46

from django.db import migrations, models
import django.db.models.deletion
import shop.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211103_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='cart',
            field=models.OneToOneField(auto_created=True, default=shop.models.order.create_cart, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerprofile', to='shop.cart', verbose_name='Корзина'),
        ),
    ]
